### ISSUE TITLE
Use E2E in Google Colab (no installation required)

### ISSUE THREAD

**Issue by playdasegunda** [jhtonyKoo/e2e_music_remastering_system#3]
I also leave here a colab that I created for your tool, in case anyone wants to try it without downloading anything, here is the link:

https://colab.research.google.com/drive/1QeFdNb-8kftC-HxHqfWnjGZa_99xYW9Y?usp=sharing

**Comment by samcate** [comment]
Hello, the link died. Do you still have the colab file by any chance?
