### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Mastering_Cloner_Wave_Unet

### ISSUE THREAD

**Issue by joupes** [jhtonyKoo/e2e_music_remastering_system#6]
Hi, would you have any ideas how the following error could be fixed? 

```
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    inf = Remastering_System_Inference(args)
  File "inference.py", line 50, in __init__
    self.reload_weights(self.mastering_cloner, \
  File "inference.py", line 72, in reload_weights
    model.load_state_dict(new_state_dict)
  File "/Users/joupes/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Mastering_Cloner_Wave_Unet:
	Missing key(s) in state_dict: "encoder.0.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.0.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.1.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.1.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.2.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.2.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.3.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.3.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.4.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.4.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.5.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.5.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.6.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.6.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.7.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.7.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.8.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.8.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.9.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.9.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.10.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.10.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.11.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.11.conv_block.0.conv1d.alias_free_downdownsample.kernel", "decoder.0.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.0.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.1.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.1.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.2.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.2.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.3.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.3.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.4.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.4.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.5.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.5.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.6.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.6.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.7.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.7.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.8.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.8.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.9.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.9.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.10.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.10.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.11.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.11.conv_block.0.conv1d.alias_free_updownsample.kernel".
```

**Comment by jhtonyKoo** [comment]
Dear user,

It seems that you're trying to modify the "configs.yaml" file at line [15](https://github.com/jhtonyKoo/e2e_music_remastering_system/blob/main/Self_Supervised_Music_Remastering_System/configs.yaml#L15) and [16](https://github.com/jhtonyKoo/e2e_music_remastering_system/blob/main/Self_Supervised_Music_Remastering_System/configs.yaml#L16) then reload the model weights. Have you tried to reload without modifying this? 
If this is not the case, could you please explain in detail the problem you're facing?

By default, the parameter names should be named something like 
- "encoder.#.conv_block.0.conv1d.alias_free_{'up' or 'down'}1d.weight"

where your error looks like you're trying to reload parameter named 
- "encoder.#.conv_block.0.conv1d.alias_free_down{'up' or 'down'}sample.kernel"

**Comment by joupes** [comment]
Hi, 

Thanks for your reply! I'm actually just trying to run the inference.py by using the example script without modifying anything. Here's the terminal command and the full error message: 

`
python inference.py \  --ckpt_dir /Users/joupes/Documents/music_remastering_system-main/model_checkpoints/ \
 --data_dir_test /Users/joupes/Documents/music_remastering_system-main/inference_samples/test_#2
`

`
/Users/joupes/Documents/music_remastering_system-main/Self_Supervised_Music_Remastering_System/config.py:90: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    inf = Remastering_System_Inference(args)
  File "inference.py", line 50, in __init__
    self.reload_weights(self.mastering_cloner, \
  File "inference.py", line 72, in reload_weights
    model.load_state_dict(new_state_dict)
  File "/Users/joupes/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Mastering_Cloner_Wave_Unet:
	Missing key(s) in state_dict: "encoder.0.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.0.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.1.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.1.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.2.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.2.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.3.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.3.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.4.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.4.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.5.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.5.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.6.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.6.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.7.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.7.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.8.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.8.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.9.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.9.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.10.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.10.conv_block.0.conv1d.alias_free_downdownsample.kernel", "encoder.11.conv_block.0.conv1d.alias_free_downupsample.kernel", "encoder.11.conv_block.0.conv1d.alias_free_downdownsample.kernel", "decoder.0.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.0.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.1.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.1.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.2.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.2.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.3.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.3.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.4.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.4.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.5.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.5.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.6.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.6.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.7.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.7.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.8.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.8.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.9.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.9.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.10.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.10.conv_block.0.conv1d.alias_free_updownsample.kernel", "decoder.11.conv_block.0.conv1d.alias_free_upupsample.kernel", "decoder.11.conv_block.0.conv1d.alias_free_updownsample.kernel".`

**Comment by jhtonyKoo** [comment]
Hello,

Long story short, you need to change the code below at line [72](https://github.com/jhtonyKoo/e2e_music_remastering_system/blob/main/inference.py#L72) of "inference.py"
originally: `model.load_state_dict(new_state_dict)`
modify this to: `model.load_state_dict(new_state_dict, strict=False)`


For some reason, [torchaudio.transforms.Resample()](https://pytorch.org/audio/main/_modules/torchaudio/transforms/_transforms.html#Resample) function ([used](https://github.com/jhtonyKoo/e2e_music_remastering_system/blob/main/Self_Supervised_Music_Remastering_System/networks/utils.py#L141) in the architecture of the Mastering Cloner) now assign kernel as a buffer and is being treated as a parameter (but without gradient). So just ignoring these kernels for resampling while reloading the pre-trained weights will solve the issue. 
Since these kernel values are not trainable parameters and are computed according to resampling rate / method, setting `strict=False` would be equivalent to as if we were able to reload the kernel weights.

Thanks for pointing out this issue! And please don't hesitate to ask any other problems.

**Comment by joupes** [comment]
That solved the problem, thank you very much!
